title: Arasu Arun
email: arasu@nyu.edu
description: ""
baseurl: ""
url: "https://arasua.run"

logo: /assets/img/fall_colors.jpeg

color-scheme: light

remote_theme: BDHU/minimalist
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

sidebar:
  - name: Email
    icon: <i class="fa-solid fa-envelope"></i>
    link: mailto:arasu@nyu.edu
  - name: Twitter
    icon: <i class="fa-brands fa-twitter"></i>
    link: https://twitter.com/arasuarun
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/arasuarun
